apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: minecraft-api-server
    namespace: {{.Release.Namespace}}
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
