apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-volume-claim
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi