apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  local:
    path: /media/bird/D/server/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bird-home-server
