apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-paper
spec:
  replicas: 1
  selector:
    matchLabels: {{.Values.podSelector.minecraft | toYaml | nindent 6}}
  template:
    metadata:
      labels: {{.Values.podSelector.minecraft | toYaml | nindent 8}}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: minecraft-container
          image: "birdman0131/minecraft-server:mc20-java21-forge"
          ports:
            - containerPort: {{.Values.ports.minecraft}}
              name: minecraft-tcp
              protocol: TCP
          volumeMounts:
            - name: minecraft-server-volume
              mountPath: /home/forge/minecraft
      volumes:
        - name: minecraft-server-volume
          persistentVolumeClaim:
            claimName: minecraft-server-volume-claim
